name: Generate Daily Deals

on:
  # schedule:
  #   - cron: '0 2 * * *'  # 02:00 UTC daily (10 PM EST / 9 PM EDT) - PAUSED
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write
  issues: write

env:
  NODE_VERSION: '20'

jobs:
  generate-deals:
    runs-on: ubuntu-latest
    environment: OPENAI_API_KEY
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch product data
        run: node scripts/fetch/index.js
        env:
          AMAZON_ASSOC_TAG: ${{ secrets.AMAZON_ASSOC_TAG }}
          ROGUE_AFFILIATE_TAG: ${{ secrets.ROGUE_AFFILIATE_TAG }}
          REP_AFFILIATE_TAG: ${{ secrets.REP_AFFILIATE_TAG }}
      
      - name: Generate daily post
        run: node scripts/generate/daily-deals.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PRIMARY_SITE_URL: ${{ secrets.PRIMARY_SITE_URL }}
          SITE_NAME: ${{ secrets.SITE_NAME }}
      
      - name: Validate content
        run: node scripts/validate/index.js
        continue-on-error: true
      
      - name: Commit and push changes
        run: |
          git config user.name "PlateDrop Bot"
          git config user.email "bot@platedrop.fit"
          git add content/deals data/deals-today.json
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit changes
          git commit -m "Daily deals: $(date +%Y-%m-%d)"
          
          # Pull with rebase to handle any remote changes
          git pull --rebase origin main || {
            echo "Rebase failed, attempting to resolve..."
            git rebase --abort
            git pull --no-rebase origin main
            git push origin main
            exit 0
          }
          
          # Push changes
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '❌ Daily deals workflow failed',
              body: `The nightly deals generation failed on ${new Date().toISOString()}.
              
              **Workflow Run:** ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
              
              Please check the logs and fix any issues.`,
              labels: ['automation', 'bug']
            })
